//$file${HSM::../Quantum_Leaps::LED_Control.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: LED_Control_Model.qm
// File:  ${HSM::../Quantum_Leaps::LED_Control.h}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${HSM::../Quantum_Leaps::LED_Control.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef LED_CONTROL_H_
#define LED_CONTROL_H_
#include"qpc.h"
typedef enum
{
    LED_DIM_SIG,
    LED_MEDIUM_SIG,
    LED_FULL_SIG,
    LED_OFF_SIG,
}LED_State;
//$declare${HSM::Led_Control} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${HSM::Led_Control} ........................................................
typedef struct {
// protected:
    QHsm super;
} Led_Control;

// protected:
QState Led_Control_initial(Led_Control * const me, void const * const par);
QState Led_Control_LED_CONTROL(Led_Control * const me, QEvt const * const e);
QState Led_Control_LED_OFF(Led_Control * const me, QEvt const * const e);
QState Led_Control_LED_DIM(Led_Control * const me, QEvt const * const e);
QState Led_Control_LED_MEDIUM(Led_Control * const me, QEvt const * const e);
QState Led_Control_LED_FULL(Led_Control * const me, QEvt const * const e);
//$enddecl${HSM::Led_Control} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#endif
