//$file${HSM::../Quantum_Leaps::LED_Control.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: LED_Control_Model.qm
// File:  ${HSM::../Quantum_Leaps::LED_Control.c}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${HSM::../Quantum_Leaps::LED_Control.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include"LED_Control.h"
//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${HSM::Led_Control} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${HSM::Led_Control} ........................................................
Led_Control Led_Control_obj;
QHsm * const Led_Control_super_QHsm =&Led_Control_obj.super;


//${HSM::Led_Control::QHSM_Ctor} .............................................
void Led_Control_QHSM_Ctor(void) {
    QHsm_ctor(Led_Control_super_QHsm,Q_STATE_CAST(&Led_Control_initial));
}

//${HSM::Led_Control::SM} ....................................................
QState Led_Control_initial(Led_Control * const me, void const * const par) {
    //${HSM::Led_Control::SM::initial}
    return Q_TRAN(&Led_Control_LED_OFF);
}

//${HSM::Led_Control::SM::LED_CONTROL} .......................................
QState Led_Control_LED_CONTROL(Led_Control * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${HSM::Led_Control::SM::LED_CONTROL::LED_OFF} ..............................
QState Led_Control_LED_OFF(Led_Control * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSM::Led_Control::SM::LED_CONTROL::LED_OFF::LED_DIM}
        case LED_DIM_SIG: {
            status_ = Q_TRAN(&Led_Control_LED_DIM);
            break;
        }
        default: {
            status_ = Q_SUPER(&Led_Control_LED_CONTROL);
            break;
        }
    }
    return status_;
}

//${HSM::Led_Control::SM::LED_CONTROL::LED_DIM} ..............................
QState Led_Control_LED_DIM(Led_Control * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSM::Led_Control::SM::LED_CONTROL::LED_DIM::LED_MEDIUM}
        case LED_MEDIUM_SIG: {
            status_ = Q_TRAN(&Led_Control_LED_MEDIUM);
            break;
        }
        //${HSM::Led_Control::SM::LED_CONTROL::LED_DIM::LED_OFF}
        case LED_OFF_SIG: {
            status_ = Q_TRAN(&Led_Control_LED_OFF);
            break;
        }
        default: {
            status_ = Q_SUPER(&Led_Control_LED_CONTROL);
            break;
        }
    }
    return status_;
}

//${HSM::Led_Control::SM::LED_CONTROL::LED_MEDIUM} ...........................
QState Led_Control_LED_MEDIUM(Led_Control * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSM::Led_Control::SM::LED_CONTROL::LED_MEDIUM::LED_FULL}
        case LED_FULL_SIG: {
            status_ = Q_TRAN(&Led_Control_LED_FULL);
            break;
        }
        //${HSM::Led_Control::SM::LED_CONTROL::LED_MEDIUM::LED_OFF}
        case LED_OFF_SIG: {
            status_ = Q_TRAN(&Led_Control_LED_OFF);
            break;
        }
        default: {
            status_ = Q_SUPER(&Led_Control_LED_CONTROL);
            break;
        }
    }
    return status_;
}

//${HSM::Led_Control::SM::LED_CONTROL::LED_FULL} .............................
QState Led_Control_LED_FULL(Led_Control * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSM::Led_Control::SM::LED_CONTROL::LED_FULL::LED_OFF}
        case LED_OFF_SIG: {
            status_ = Q_TRAN(&Led_Control_LED_OFF);
            break;
        }
        //${HSM::Led_Control::SM::LED_CONTROL::LED_FULL::LED_DIM}
        case LED_DIM_SIG: {
            status_ = Q_TRAN(&Led_Control_LED_DIM);
            break;
        }
        default: {
            status_ = Q_SUPER(&Led_Control_LED_CONTROL);
            break;
        }
    }
    return status_;
}
//$enddef${HSM::Led_Control} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${HSM::Led_Control::Opeation} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//$enddef${HSM::Led_Control::Opeation} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${HSM::Led_Control::QHSM_init}
//$define${HSM::Led_Control::QHSM_Ctor}
//$define${HSM::Led_Control::super_QHsm}
