//$file${HSM::../Quantum_Leaps::LED_Control.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: LED_Control_Model.qm
// File:  ${HSM::../Quantum_Leaps::LED_Control.c}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${HSM::../Quantum_Leaps::LED_Control.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include"LED_Control.h"
#include "main.h"
extern TIM_HandleTypeDef htim2;
//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${HSM::LED_FULL} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${HSM::LED_FULL} ...........................................................
uint16_t LED_FULL =255;
//$enddef${HSM::LED_FULL} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${HSM::LED_MEDIUM} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${HSM::LED_MEDIUM} .........................................................
uint16_t LED_MEDIUM =125;
//$enddef${HSM::LED_MEDIUM} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${HSM::LED_DIM} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${HSM::LED_DIM} ............................................................
uint16_t LED_DIM =50;
//$enddef${HSM::LED_DIM} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${HSM::LED_OFF} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${HSM::LED_OFF} ............................................................
uint16_t LED_OFF =0;
//$enddef${HSM::LED_OFF} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${HSM::super_Led_Control} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${HSM::super_Led_Control} ..................................................
QHsm  *const super_Led_Control =&Led_Control_obj.super;
//$enddef${HSM::super_Led_Control} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${HSM::Led_Control} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${HSM::Led_Control} ........................................................
Led_Control Led_Control_obj;

//${HSM::Led_Control::SM} ....................................................
QState Led_Control_initial(Led_Control * const me, void const * const par) {
    //${HSM::Led_Control::SM::initial}
    LED_Intencity_Control(LED_OFF);
    return Q_TRAN(&Led_Control_LED_OFF);
}

//${HSM::Led_Control::SM::LED_CONTROL} .......................................
QState Led_Control_LED_CONTROL(Led_Control * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${HSM::Led_Control::SM::LED_CONTROL::LED_OFF} ..............................
QState Led_Control_LED_OFF(Led_Control * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSM::Led_Control::SM::LED_CONTROL::LED_OFF::LED_ON}
        case LED_ON_SIG: {
            LED_Intencity_Control(LED_DIM);
            status_ = Q_TRAN(&Led_Control_LED_DIM);
            break;
        }
        default: {
            status_ = Q_SUPER(&Led_Control_LED_CONTROL);
            break;
        }
    }
    return status_;
}

//${HSM::Led_Control::SM::LED_CONTROL::LED_DIM} ..............................
QState Led_Control_LED_DIM(Led_Control * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSM::Led_Control::SM::LED_CONTROL::LED_DIM::LED_ON}
        case LED_ON_SIG: {
            LED_Intencity_Control(LED_MEDIUM);
            status_ = Q_TRAN(&Led_Control_LED_MEDIUM);
            break;
        }
        //${HSM::Led_Control::SM::LED_CONTROL::LED_DIM::LED_OFF}
        case LED_OFF_SIG: {
            LED_Intencity_Control(LED_OFF);
            status_ = Q_TRAN(&Led_Control_LED_OFF);
            break;
        }
        default: {
            status_ = Q_SUPER(&Led_Control_LED_CONTROL);
            break;
        }
    }
    return status_;
}

//${HSM::Led_Control::SM::LED_CONTROL::LED_MEDIUM} ...........................
QState Led_Control_LED_MEDIUM(Led_Control * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSM::Led_Control::SM::LED_CONTROL::LED_MEDIUM::LED_ON}
        case LED_ON_SIG: {
            LED_Intencity_Control(LED_FULL);
            status_ = Q_TRAN(&Led_Control_LED_FULL);
            break;
        }
        //${HSM::Led_Control::SM::LED_CONTROL::LED_MEDIUM::LED_OFF}
        case LED_OFF_SIG: {
            LED_Intencity_Control(LED_OFF);
            status_ = Q_TRAN(&Led_Control_LED_OFF);
            break;
        }
        default: {
            status_ = Q_SUPER(&Led_Control_LED_CONTROL);
            break;
        }
    }
    return status_;
}

//${HSM::Led_Control::SM::LED_CONTROL::LED_FULL} .............................
QState Led_Control_LED_FULL(Led_Control * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSM::Led_Control::SM::LED_CONTROL::LED_FULL::LED_OFF}
        case LED_OFF_SIG: {
            LED_Intencity_Control(LED_OFF);
            status_ = Q_TRAN(&Led_Control_LED_OFF);
            break;
        }
        //${HSM::Led_Control::SM::LED_CONTROL::LED_FULL::LED_ON}
        case LED_ON_SIG: {
            LED_Intencity_Control(LED_DIM);
            status_ = Q_TRAN(&Led_Control_LED_DIM);
            break;
        }
        default: {
            status_ = Q_SUPER(&Led_Control_LED_CONTROL);
            break;
        }
    }
    return status_;
}
//$enddef${HSM::Led_Control} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${HSM::LED_Intencity_Control} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${HSM::LED_Intencity_Control} ..............................................
void LED_Intencity_Control(uint16_t duty_uint16_t) {
    __HAL_TIM_SET_COMPARE(&htim2,TIM_CHANNEL_1,duty_uint16_t);
}
//$enddef${HSM::LED_Intencity_Control} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${HSM::Led_Control_Ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${HSM::Led_Control_Ctor} ...................................................
void Led_Control_Ctor(void) {
    QHsm_ctor(super_Led_Control,Q_STATE_CAST(&Led_Control_initial));
}
//$enddef${HSM::Led_Control_Ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

